name: Data Crawler

on:
  workflow_dispatch:
  schedule:
    - cron:  '35 * * * *'  # once a day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests bs4

    - name: Run crawler
      run: python crawler.py

    - name: Commit and push if it changed
      run: |
        git config --local user.email "bruceewue@gmail.com"
        git config --local user.name "Bruce Wu"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Updated data"
        git push
